GET http://localhost:3300/radnici

###


POST http://localhost:3300/radnici
Content-Type: application/json

{
"ime": "mira",
"prezime": "mark"
}

###

GET http://localhost:3300/5f3fe1cc05040d1100e2df32


###
DELETE http://localhost:3300/5f3fe1cc05040d1100e2df32